name: Update YML with Markup

on:
  schedule:
    - cron: '0 */4 * * *'  # каждые 4 часа
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Create Python script
        run: |
          echo "import requests" > script.py
          echo "import xml.etree.ElementTree as ET" >> script.py
          echo "url = 'https://al-style.kz/upload/catalog_export/al_style_catalog.php'" >> script.py
          echo "response = requests.get(url)" >> script.py
          echo "with open('original.xml', 'wb') as f: f.write(response.content)" >> script.py
          echo "tree = ET.parse('original.xml')" >> script.py
          echo "root = tree.getroot()" >> script.py
          echo "markup = 1.35" >> script.py
          echo "for offer in root.findall('.//offer'):" >> script.py
          echo "    price = offer.find('price')" >> script.py
          echo "    if price is not None:" >> script.py
          echo "        try:" >> script.py
          echo "            original_price = float(price.text)" >> script.py
          echo "            new_price = round(original_price * markup, 2)" >> script.py
          echo "            price.text = str(new_price)" >> script.py
          echo "        except ValueError: pass" >> script.py
          echo "tree.write('allstyle_with_markup.yml', encoding='utf-8', xml_declaration=True)" >> script.py

      - name: Run script
        run: python script.py

      - name: Commit and push updated YML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add allstyle_with_markup.yml
          git commit -m "Update YML with 35% markup"
          git push
